---

- hosts: web-servers
  become: true
  user: ubuntu
  tasks:

    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: copy file to server
      copy:
        src: somefile.txt
        dest: /home/ubuntu/ansible-files/
        owner: ubuntu
        group: ubuntu
        mode: 0644

- hosts: pnm-test-servers
  become: true
  user: testuser
  tasks:

    - name: update apt packages
      apt:
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]
